java -classpath "C:\Users\chriswho\IdeaProjects\ownership-analyzer\soot\soot-trunk.jar;C:\Users\chriswho\IdeaProjects\ownership-analyzer\out\production\ownership-analysis" AnalysisMain -cp C:\Users\chriswho\IdeaProjects\sales-taxes\bin thoughtworks.problem.salesTax.application.Application
java -classpath "C:\Users\chriswho\IdeaProjects\ownership-analyzer\soot\soot-trunk.jar;C:\Users\chriswho\IdeaProjects\ownership-analyzer\out\production\ownership-analysis" AnalysisMain -cp C:\Users\chriswho\IdeaProjects\sales-taxes\bin thoughtworks.problem.salesTax.application.CategoryLookup
java -classpath "C:\Users\chriswho\IdeaProjects\ownership-analyzer\soot\soot-trunk.jar;C:\Users\chriswho\IdeaProjects\ownership-analyzer\out\production\ownership-analysis" AnalysisMain -cp C:\Users\chriswho\IdeaProjects\sales-taxes\bin thoughtworks.problem.salesTax.application.FileParser
java -classpath "C:\Users\chriswho\IdeaProjects\ownership-analyzer\soot\soot-trunk.jar;C:\Users\chriswho\IdeaProjects\ownership-analyzer\out\production\ownership-analysis" AnalysisMain -cp C:\Users\chriswho\IdeaProjects\sales-taxes\bin thoughtworks.problem.salesTax.application.InputData
java -classpath "C:\Users\chriswho\IdeaProjects\ownership-analyzer\soot\soot-trunk.jar;C:\Users\chriswho\IdeaProjects\ownership-analyzer\out\production\ownership-analysis" AnalysisMain -cp C:\Users\chriswho\IdeaProjects\sales-taxes\bin thoughtworks.problem.salesTax.application.Peer
java -classpath "C:\Users\chriswho\IdeaProjects\ownership-analyzer\soot\soot-trunk.jar;C:\Users\chriswho\IdeaProjects\ownership-analyzer\out\production\ownership-analysis" AnalysisMain -cp C:\Users\chriswho\IdeaProjects\sales-taxes\bin thoughtworks.problem.salesTax.application.Printer
java -classpath "C:\Users\chriswho\IdeaProjects\ownership-analyzer\soot\soot-trunk.jar;C:\Users\chriswho\IdeaProjects\ownership-analyzer\out\production\ownership-analysis" AnalysisMain -cp C:\Users\chriswho\IdeaProjects\sales-taxes\bin thoughtworks.problem.salesTax.application.Receipt
java -classpath "C:\Users\chriswho\IdeaProjects\ownership-analyzer\soot\soot-trunk.jar;C:\Users\chriswho\IdeaProjects\ownership-analyzer\out\production\ownership-analysis" AnalysisMain -cp C:\Users\chriswho\IdeaProjects\sales-taxes\bin thoughtworks.problem.salesTax.application.Rep
java -classpath "C:\Users\chriswho\IdeaProjects\ownership-analyzer\soot\soot-trunk.jar;C:\Users\chriswho\IdeaProjects\ownership-analyzer\out\production\ownership-analysis" AnalysisMain -cp C:\Users\chriswho\IdeaProjects\sales-taxes\bin thoughtworks.problem.salesTax.application.TransactionHandler
 
java -classpath "C:\Users\chriswho\IdeaProjects\ownership-analyzer\soot\soot-trunk.jar;C:\Users\chriswho\IdeaProjects\ownership-analyzer\out\production\ownership-analysis" AnalysisMain -cp C:\Users\chriswho\IdeaProjects\sales-taxes\bin thoughtworks.problem.salesTax.products.Book
java -classpath "C:\Users\chriswho\IdeaProjects\ownership-analyzer\soot\soot-trunk.jar;C:\Users\chriswho\IdeaProjects\ownership-analyzer\out\production\ownership-analysis" AnalysisMain -cp C:\Users\chriswho\IdeaProjects\sales-taxes\bin thoughtworks.problem.salesTax.products.Food
java -classpath "C:\Users\chriswho\IdeaProjects\ownership-analyzer\soot\soot-trunk.jar;C:\Users\chriswho\IdeaProjects\ownership-analyzer\out\production\ownership-analysis" AnalysisMain -cp C:\Users\chriswho\IdeaProjects\sales-taxes\bin thoughtworks.problem.salesTax.products.Medical
java -classpath "C:\Users\chriswho\IdeaProjects\ownership-analyzer\soot\soot-trunk.jar;C:\Users\chriswho\IdeaProjects\ownership-analyzer\out\production\ownership-analysis" AnalysisMain -cp C:\Users\chriswho\IdeaProjects\sales-taxes\bin thoughtworks.problem.salesTax.products.Other
java -classpath "C:\Users\chriswho\IdeaProjects\ownership-analyzer\soot\soot-trunk.jar;C:\Users\chriswho\IdeaProjects\ownership-analyzer\out\production\ownership-analysis" AnalysisMain -cp C:\Users\chriswho\IdeaProjects\sales-taxes\bin thoughtworks.problem.salesTax.products.Product
java -classpath "C:\Users\chriswho\IdeaProjects\ownership-analyzer\soot\soot-trunk.jar;C:\Users\chriswho\IdeaProjects\ownership-analyzer\out\production\ownership-analysis" AnalysisMain -cp C:\Users\chriswho\IdeaProjects\sales-taxes\bin thoughtworks.problem.salesTax.products.ProductFactory
 
java -classpath "C:\Users\chriswho\IdeaProjects\ownership-analyzer\soot\soot-trunk.jar;C:\Users\chriswho\IdeaProjects\ownership-analyzer\out\production\ownership-analysis" AnalysisMain -cp C:\Users\chriswho\IdeaProjects\sales-taxes\bin thoughtworks.problem.salesTax.shoppingCart.CustomerCart
java -classpath "C:\Users\chriswho\IdeaProjects\ownership-analyzer\soot\soot-trunk.jar;C:\Users\chriswho\IdeaProjects\ownership-analyzer\out\production\ownership-analysis" AnalysisMain -cp C:\Users\chriswho\IdeaProjects\sales-taxes\bin thoughtworks.problem.salesTax.shoppingCart.ShoppingCart

java -classpath "C:\Users\chriswho\IdeaProjects\ownership-analyzer\soot\soot-trunk.jar;C:\Users\chriswho\IdeaProjects\ownership-analyzer\out\production\ownership-analysis" AnalysisMain -cp "C:\Users\chriswho\IdeaProjects\sales-taxes\bin;C:\Program Files (x86)\JetBrains\IntelliJ IDEA 15.0.1\lib\junit-4.12.jar" thoughtworks.problem.salesTax.test.CategoryLookupTest
